Imports MySql.Data.MySqlClient


Public Class AuthManager

    Public Shared CurrentFullName As String = ""

    ' --- LOGIN LOGIC ---
    Public Shared Function LoginUser(username As String, password As String) As String
        Dim role As String = ""
        Try
            openConn()
            Dim query As String = "SELECT UserID, AccountType FROM tblUsers WHERE Username = @user AND Password = @pass"
            Dim cmd As New MySqlCommand(query, conn)
            cmd.Parameters.AddWithValue("@user", username)
            cmd.Parameters.AddWithValue("@pass", password)

            Dim reader As MySqlDataReader = cmd.ExecuteReader()
            If reader.HasRows Then
                reader.Read()
                CurrentUserID = Convert.ToInt32(reader("UserID"))
                role = reader("AccountType").ToString()
                CurrentRole = role
            End If
            reader.Close()
        Catch ex As Exception
            MsgBox("Database Error: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            closeConn()
        End Try
        Return role
    End Function

    ' --- CHECK IF EMAIL EXISTS (THE FAILSAFE FIX) ---
    Public Shared Function IsEmailTaken(email As String) As Boolean
        Dim isTaken As Boolean = False
        Try
            openConn()
            ' We ONLY check tblUsers because that is where RegisterUser saves the email
            Dim query As String = "SELECT COUNT(*) FROM tblUsers WHERE Email = @email"
            Dim cmd As New MySqlCommand(query, conn)
            cmd.Parameters.AddWithValue("@email", email)

            Dim count As Integer = Convert.ToInt32(cmd.ExecuteScalar())

            ' If the email is found, flag it as taken
            If count > 0 Then
                isTaken = True
            End If
        Catch ex As Exception
            ' If there is an error (like a missing column), SHOW IT and BLOCK the registration
            MsgBox("Email Check Error: " & ex.Message, MsgBoxStyle.Critical)
            Return True '<-- FAILSAFE: Pretend the email is taken to stop the OTP from sending
        Finally
            closeConn()
        End Try
        Return isTaken
    End Function

    ' --- REGISTER LOGIC ---
    Public Shared Function RegisterUser(fullName As String, username As String, password As String, role As String, email As String, city As String, barangay As String) As Boolean
        Try
            openConn()

            ' 1. INSERT INTO tblUsers (The Login Account)
            ' Note: I added FullName, Email, City, Barangay here since they are in your screenshot {B44D9A30-FD42-419F-A2B3-FCB35C4043D8}.png
            Dim userQuery As String = "INSERT INTO tblUsers (FullName, Username, Password, AccountType, Email, City, Barangay) " &
                                     "VALUES (@name, @user, @pass, @role, @email, @city, @brgy)"

            Dim cmdUser As New MySqlCommand(userQuery, conn)
            cmdUser.Parameters.AddWithValue("@name", fullName)
            cmdUser.Parameters.AddWithValue("@user", username)
            cmdUser.Parameters.AddWithValue("@pass", password)
            cmdUser.Parameters.AddWithValue("@role", role)
            cmdUser.Parameters.AddWithValue("@email", email)
            cmdUser.Parameters.AddWithValue("@city", city)
            cmdUser.Parameters.AddWithValue("@brgy", barangay)

            cmdUser.ExecuteNonQuery()

            ' 2. GET THE NEW UserID generated by MySQL
            Dim getIDCmd As New MySqlCommand("SELECT LAST_INSERT_ID()", conn)
            Dim newUserID As Integer = Convert.ToInt32(getIDCmd.ExecuteScalar())

            ' 3. AUTOMATION: Insert into the Role-Specific Profile Table
            Dim profileQuery As String = ""

            ' Matches the role string sent from your frmRegister (Worker or Employer)
            If role = "Worker" Then
                profileQuery = "INSERT INTO tblworkers (UserID, FullName) VALUES (@uid, @name)"
            Else
                ' This fixes the error you saw in {5E4B4D41-0144-4A7D-8AA4-A06E3DD88BFE}.png
                profileQuery = "INSERT INTO tblemployeers (UserID, FullName) VALUES (@uid, @name)"
            End If

            Dim cmdProfile As New MySqlCommand(profileQuery, conn)
            cmdProfile.Parameters.AddWithValue("@uid", newUserID)
            cmdProfile.Parameters.AddWithValue("@name", fullName)

            cmdProfile.ExecuteNonQuery()

            Return True

        Catch ex As Exception
            MsgBox("Database Error: " & ex.Message, MsgBoxStyle.Critical)
            Return False
        Finally
            closeConn()
        End Try
    End Function

End Class